export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  PRINCIPAL: 'principal',
  TEACHER: 'teacher',
  CLASS_TEACHER: 'class_teacher',
  ACCOUNTANT: 'accountant',
  LIBRARIAN: 'librarian',
  ADMISSION_STAFF: 'admission_staff',
  STUDENT: 'student',
  PARENT: 'parent',
};

export const STAFF_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.ADMIN,
  ROLES.PRINCIPAL,
  ROLES.TEACHER,
  ROLES.CLASS_TEACHER,
  ROLES.ACCOUNTANT,
  ROLES.LIBRARIAN,
  ROLES.ADMISSION_STAFF,
];

export const STAFF_MANAGERS = [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PRINCIPAL];
export const SETTINGS_MANAGERS = [ROLES.SUPER_ADMIN, ROLES.ADMIN];

export const ACCESS = {
  dashboard: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.CLASS_TEACHER, ROLES.ACCOUNTANT, ROLES.LIBRARIAN, ROLES.ADMISSION_STAFF],
  students_view: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.CLASS_TEACHER, ROLES.ADMISSION_STAFF, ROLES.ACCOUNTANT],
  students_manage: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PRINCIPAL, ROLES.ADMISSION_STAFF, ROLES.CLASS_TEACHER],
  classes: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PRINCIPAL, ROLES.ADMISSION_STAFF],
  subjects: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.CLASS_TEACHER],
  teachers: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PRINCIPAL],
  subject_allocation: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PRINCIPAL],
  timetable_manage: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PRINCIPAL],
  timetable_view: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.CLASS_TEACHER],
  substitutions: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PRINCIPAL],
  attendance: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.CLASS_TEACHER],
  leave: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PRINCIPAL, ROLES.CLASS_TEACHER, ROLES.TEACHER],
  fees_structure: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  fees_assign: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT],
  fees_list: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT, ROLES.CLASS_TEACHER],
  payments: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT],
  expenses: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.ACCOUNTANT],
  homework: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.CLASS_TEACHER],
  exams: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.CLASS_TEACHER],
  report_cards: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.CLASS_TEACHER, ROLES.ACCOUNTANT],
  library: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.LIBRARIAN],
  circulars: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PRINCIPAL, ROLES.TEACHER, ROLES.CLASS_TEACHER],
  staff: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PRINCIPAL],
  settings: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  reports: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.PRINCIPAL, ROLES.ACCOUNTANT],
};

export const canAccessRole = (role, accessKey) => {
  if (!role) return false;
  const allowed = ACCESS[accessKey] || [];
  return allowed.includes(role);
};
